version: '3.4'

services:
  application:
    restart: unless-stopped
    image: financial_portfolios
    build: .
    environment:
      - NODE_ENV=production
      - AVAK
    ports:
      - 9999:3000
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
      
  mongodb:
    restart: unless-stopped
    image: mongo:latest
    command: mongod --port 27018
    ports:
      - 27018:27018
    volumes:
      - data:/data/db

volumes:
  data:
